# Site settings
title: Cristian Ghiorzi
email: cri.ghiorzi@gmail.com
url: https://xpoke-glitch.github.io/
description: "Cristian Ghiorzi Game Developer Portfolio"
keywords: "Game Developer, Unity, Unreal Engine, Portfolio, Cristian, Ghiorzi, Programmer, Developer"
skills: "Game Developer - Unity - Unreal Engine"
meta_author: Cristian Ghiorzi

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Cristian Ghiorzi
  location: Location
  social: Around the Web
  credits: Contact me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/cristian-ghiorzi-955a55240/
  - title: github
    url: https://github.com/xPoke-glitch
  - title: itch-io
    url: https://pokedev.itch.io/

# Postal address (add as many lines as necessary)
address:
  - line: Varano de' Melegari, Parma, Italy

# Credits content
credits: 'You can email me here at cri.ghiorzi@gmail.com.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
